### ISSUE TITLE
📄🚀 – Clarify description of `fare_transactions.fare_capped`

### ISSUE THREAD

**Issue by jaygordon** [TIDES-transit/TIDES#110]
**Describe the feature you want and how it meets your needs or solves a problem**

As a future TIDES user, the meaning of `fare_transactions.fare_capped` isn't clear to me so it may be helpful (to me and perhaps others) clarify its description.

This column’s description reads “Indicates if fare capping is in effect (fare capping options defined by transit agency).” Does this mean that this specific card/ticket/etc. has been capped at this time of this transaction, or does it mean that the agency’s policy is to cap fares for this fare product when some stored-value limit is reached? 

**Describe the solution you'd like**

Reword the description to clarify the above.

**Comment by gabriel-korbato** [comment]
In today's discussion, we decided to have this field mean that the specific transaction was fare-capped.
