### ISSUE TITLE
🐛📄 – Move `currency_type` from `fare_transactions` to a new metadata table.

### ISSUE THREAD

**Issue by gabriel-korbato** [TIDES-transit/TIDES#111]
**Describe the problem**
The `fare_transactions` table includes a `currency_type` field.  Is there any transit agency that handles multiple currencies?  I'm not aware of any, so it seems that repeating this for every fare transaction record isn't efficient. 

**Possible Solutions**
Move the `currency_type` field from the `fare_transactions` table to a new single-row agency metadata table.  We could name the new table `agency` or `system`, etc.  In addition to `currency_type`, this new table could have other useful parameters such as the agency's time zone (again, assuming one), website, etc.

**Comment by jlstpaul** [comment]
At the very least, it should be optional.  But I am also not opposed to removing it if others don't see a need for it.
