### ISSUE TITLE
📄🚀 – Accommodate unscheduled trips in `stop_visits`

### ISSUE THREAD

**Issue by jaygordon** [TIDES-transit/TIDES#112]
**Describe the feature you want and how it meets your needs or solves a problem**

As a software vendor who produces cleaned/enriched vehicle-history data, I want `stop_visits.stop_sequence` to be optional so that vehicle trips can be represented in TIDES when we don't know what pattern or scheduled trip the vehicle is serving.

**Describe the solution you'd like**

I'd like for `stop_visits.stop_sequence` to be optional.

**Describe alternatives you've considered**

A bogus value could be entered into the column to satisfy the requirement, but that could be misleading.

**Additional context and sample data**

I've worked with transit data where we have a history of a bus's trajectory from heartbeat/breadcrumb data, and we see boardings on that vehicle by temporally matching its farebox's transactions with the vehicle history, but neither data source records the bus's route, direction, pattern, or scheduled trip. There can also be unscheduled vehicle trips in a transit system that otherwise includes schedule information in their AVL and/or AFC data, such as if emergency shuttles are deployed in an improvised way. In the former case, there might be a pattern and/or trip but it's unknown, and in the latter case there isn't a scheduled a trip and perhaps not even a pattern. Both would be accommodated by making the `stop_sequence` field optional.

**Comment by e-lo** [comment]
> Describe alternatives you've considered
> 
> A bogus value could be entered into the column to satisfy the requirement, but that could be misleading.

Rather than make it optional, what if we explicitly mapped `UNKNOWN` to a value of -1 or 0 ?

**Comment by jaygordon** [comment]
> Rather than make it optional, what if we explicitly mapped `UNKNOWN` to a value of -1 or 0 ?

I prefer -1 to 0 because someone with a coder mindset could think `stop_sequence` starts at zero.

If we're going to mix literal values (1, 2...) and mappings (-1), should there be one mapping for "unknown," such as when a vehicle was serving some scheduled trip but we don't know which one, and another for "none" or "N/A," such as when we know the trip was unscheduled and improvised? That could be overkill, just putting it out there.

**Comment by jlstpaul** [comment]
Issue #88 proposed that stop_sequence be optional. I think that is the correct approach, especially if paired with a best practice/feature set that _requires_ the stop_sequence when it is known.

**Comment by mpaine-act** [comment]
> emergency shuttles are deployed in an improvised way. In the former case, there might be a pattern and/or trip but it's unknown, and in the latter case there isn't a scheduled a trip and perhaps not even a pattern.

Since TIDES is dealing with historical information, could the historical GTFS.stop_times.txt file be updated to provide a trip stop pattern to fulfill the missing stop_sequence for any unscheduled trip?   Is that an acceptable alternative solution?

**Comment by jaygordon** [comment]
This issue and its title were referring to `stop_times` but I meant `stop_vistits`. I just corrected that.

**Comment by jaygordon** [comment]
On yesterday's call, Erik noted that `stop_visits.stop_sequence` is part of a compound primary key, so if we make that field optional we'd need to find another way of making a PK for `stop_visits`.

At present, the PK is   `service_date`, `trip_id_performed`, `stop_sequence`, `vehicle_id`.

The group discussed a few options for a primary key on yesterday's call:

1. We could add a new column that indicates the sequence of a `stop_visit` within its actual/performed trip, regardless of whether the visit was scheduled. This works well for us at Korbato, where a `seq_in_trip` field is auto-incremented from 1 at the start of each performed trip, and `seq_in_pattern` is nullable and might differ from `seq_in_trip` if the vehicle skips any scheduled stops or makes any unscheduled stops. 
2. @jlstpaul suggested including arrival time in the primary key. This has the benefit of not adding a new field, but we'd need to consider whether two visits on the same trip might have the same arrival time or a null arrival time. If the `stop_visits` data have been cleaned, perhaps the spec could require non-null, unique arrival times, but there could be cases where we might not want to require that (such as a null arrival time if it's inferred that a stop was served or passed but the time isn't know or can't be confidently inferred).
3. The idea of using the stop ID in the primary key came up, but there are some bus routes that serve the same stop more than once (such as the WMATA C21 or the MBTA 120).

**Comment by jlstpaul** [comment]
> We could add a new column that indicates the sequence of a `stop_visit` within its actual/performed trip, regardless of whether the visit was scheduled. This works well for us at Korbato, where a `seq_in_trip` field is auto-incremented from 1 at the start of each performed trip, and `seq_in_pattern` is nullable and might differ from `seq_in_trip` if the vehicle skips any scheduled stops or makes any unscheduled stops.

I'd like to recommend this approach as follows:
- add new `trip_stop_sequence` to `stop_visits` table, and to `vehicle_locations`, `passenger_events`, and `fare_transactions` tables.  This would be the sequence of the stop in the trip as operated, irregardless of the schedule
- rename the stop_sequence field to scheduled_stop_sequence. It would continue to be the reference to the GTFS `stop_times.stop_sequence` field and would be optional.
- change the primary key on `stop_visits` to `service_date`, `trip_id_performed`, **`trip_stop_sequence`**, `vehicle_id`

**Comment by mpaine-act** [comment]
Since vehicle_id can be null in some cases, we assuming the primary key might include nulls in the composite keys which is not allowed in PKs for most SQL systems (Oracle, SQL Server, etc.)

**Comment by jlstpaul** [comment]
> Since vehicle_id can be null in some cases, we assuming the primary key might include nulls in the composite keys which is not allowed in PKs for most SQL systems (Oracle, SQL Server, etc.)

`stop_visits.vehicle_id` is listed as required.  In what situation would it be null?  Would we have a 'stop_visits' record that does not have a vehicle associated with it?
