### ISSUE TITLE
🐛📄 – Clarify the meaning of boarding and alighting fields in `stop_visits`

### ISSUE THREAD

**Issue by gabriel-korbato** [TIDES-transit/TIDES#113]
**Describe the problem**
The `stop_visits` table has `boarding_1`, `alighting_1`, `boarding_2`, and `alighting_2` columns.  The documentation for the first two of these refers to the vehicle's "front-most" and "right-most" doors.  These terms are confusing, e.g. which door is most to the right?  When should boardings and alightings be reported for front vs right doors? 

**Possible Solutions**
Clarify the meaning, interpretation, and use of these fields in the documentation.  For example:

- `boarding_1` - Number of riders who entered through the vehicle's front doors (in vehicles with doors opening on only one side, or when passengers primarily board through the front, as is typical with buses) or the vehicle's right doors (in vehicles with doors on both sides, or when passengers board through all doors, as is typical with trains).
- `alighting_1` - Number of riders who exited through the vehicle's front doors (in vehicles with doors opening on only one side, or when passengers primarily board through the front, as is typical with buses) or the vehicle's right doors (in vehicles with doors on both sides, or when passengers board through all doors, as is typical with trains).
- `boarding_2` - Number of riders who entered through other doors, such as a bus's rear door when `boarding_1` captures the front door, or a train's left doors when `boarding_1` captures right doors.
- `alighting_2` - Number of riders who exited through other doors, such as a bus's rear door when `alighting_1` captures the front door, or a train's left doors when `alighting_1` captures right doors.

**Comment by e-lo** [comment]
Agree that this is confusing. Suggest we achieve consistency with various [GTFS Vehicles proposals](https://docs.google.com/document/d/156RiBjI6FnWJvO8_XWX11Q9nLdOiBdS_rilA-oamlv8/edit#heading=h.a2xppibtocyz) and potentially have this sit in some sort of *experimental* zone of purgatory until such a time that relevant parts of GTFS Vehicles is adopted to make sure we have consistency.

**Comment by jlstpaul** [comment]
Agree that this may be an element that evolves in tandem with GTFS.   For now, @gabriel-korbato suggested clarifications of the definitions seem reasonable.

**Comment by mpaine-act** [comment]
Ferries boats have front and rear doors for cars (aka riders).  I do like the numbering system instead of left/right to designate main/secondary access doors or gates.
