### ISSUE TITLE
📄🚀 – Clarify the meaning of "revenue" in `station_activities` and `stop_visits`

### ISSUE THREAD

**Issue by jaygordon** [TIDES-transit/TIDES#114]
**Describe the feature you want and how it meets your needs or solves a problem**

As a prospective TIDES user, I'm uncertain of the meaning of the various revenue fields in `stop_visits` and `station_activities` so I'd like the meaning to be clarified in the documentation.

**Additional context and sample data**

I can think of two meanings for these fields, and there might be more.

1. The amount of revenue taken in at the specified stop visit or station/time period. For example, ticket and pass sales at station vending machines (even if those tickets or passes weren't used at that time and place), and onboard payments in the form of cash, bank card, or mobile-payment transactions. This would exclude any stored-value or pass rides, as revenue would have already been collected at some previous time and place.
2. The monetary value of revenues, possibly previously obtained by the agency, redeemed for ridership at the specified stop visit or station/time period. This would include some of the same things as the previous bullet (such as onboard cash, bank-card or mobile-payment), would exclude others (such as sales of tickets or passes that weren't used at that time and place), and would additionally include stored-value validations and ticket redemptions (and, if calculated in hindsight, the portion of a pass’s price allocated to some ride).

The first seems like the more obvious interpretation but I've seen several cases of an agency wanting to know the second.

**Comment by jlstpaul** [comment]
The association of revenue to rides or locations is not at all straightforward and varies not only among agencies, but across modes and fare collection systems within the same agency and over time.  The fundamental objective the revenue fields on `stop_visits` should be to record “the total revenue that the agency assigns to the customers that are associated with the boarding and alighting fields.”  How that assignment is made needs to be flexible.  

I suspect this will vary even from iteration to iteration of the same data within an agency.  For example, the raw data for an agency may capture just the cash and stored value revenue directly associated with the boardings.  And that would be the data aggregated into the `stop_visit`.  Perhaps another iteration of that same data will take the count of pass uses and allocate the backend revenue from those passes to each of the rides on the pass and then assign a new value to `transaction_revenue_smartcard`.  

The same could be said for the revenue fields on `station_activities`.  Perhaps in an initial iteration of raw data, these fields represent the monetary value collected at that station and in a later iteration of the same data, these fields represent the allocation of system revenues that should be assigned to that station for analysis purposes.
