### ISSUE TITLE
🐛📄 – Rename fields for clarity

### ISSUE THREAD

**Issue by gabriel-korbato** [TIDES-transit/TIDES#115]
**Describe the problem**
Some column names could be confusing.  For example:

- `fare_transactions.fare_media_id` does not identify the fare media (e.g. smartcard, paper ticket, cash) but rather the specific card or ticket used.
- `fare_transactions.group_size` refers to the number of riders covered by the fare transaction, and not a group of fare transactions.
- `fare_transactions.media_type` refers to the fare medium (e.g. smartcard, paper ticket, cash), and not the type of medium (e.g. type of smart card, type of paper ticket)
- `trips_performed.in_service` is not a boolean (yes/no) as suggested by its name, but actually describes the status of the service
- `devices.stop_id` refers to a device's location, which can be a stop but also a station entrance or somewhere else
- `devices.device_type` refers to the type of data collection system (AFC, AVL, APC) rather than the type of device (farebox, fare gate, fare vending machine, infrared APC, overhead APC, etc.)

**Possible Solutions**

- Rename `fare_transactions.fare_media_id` to `token_id`
- Rename `fare_transactions.group_size` to `num_riders`
- Rename `fare_transactions.media_type` to `fare_medium`.  Here I note that "media" is plural and "medium" is singular, but I also acknowledge that "media" is used by some agencies already.  
- Rename `trips_performed.in_service` to `service_status`.
- Rename `devices.stop_id` to `place_id`.
- Rename `devices.device_type` to `system_type`, or better yet, keep the name but redefine the enum to contain device types (farebox, fare gate, fare vending machine, infrared APC, overhead APC, etc.), since that is very useful information.

**Comment by e-lo** [comment]
Suggest that we keep everything as consistent with possible with GTFS - even when it might not be as clear.

That would keep (iff they are consistent with the understanding in GTFS...):

- [`fare_media_id` ](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#fare_mediatxt)
- [`fare_media_type`](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#fare_mediatxt)
- `stop_id` (which goes beyond stops already in GTFS)

Note: media can be singular or plural and GTFS Fares v2 uses media.

**Comment by gabriel-korbato** [comment]
Interesting, thanks.  So what we're calling `media_type` should be called `fare_media_id` to make it compatible with GTFS, rather than `fare_medium` as I suggested.

**Comment by Danishswag** [comment]
Should we add this to the v1 milestone? It seems like something we should align on before the v1 release since changing field names isn't backwards compatible
