### ISSUE TITLE
📄🚀 – Specify foreign key relationships that already exist but aren't listed explicitly

### ISSUE THREAD

**Issue by jaygordon** [TIDES-transit/TIDES#131]
**Describe the feature you want and how it meets your needs or solves a problem**

As a software developer likely to use and produce TIDES data, I notice some internal foreign key relationships that aren't specified in the spec but that could be helpful to add.

**Describe the solution you'd like**

I'd like to add these foreign keys to the spec.

**Additional context and sample data**

While working in issue #112 I noticed that `fare_transactions`, `vehicle_locations`, and `passenger_events` can sometimes or always (depending on the table) reference a `stop_visit` using the fields `(service_date, trip_id_performed, trip_stop_sequence)`. There may be other foreign key relationships that already exist and aren't specified but I haven't done an exhaustive check.

**Comment by gabriel-korbato** [comment]
I started working on the specific foreign reference @jaygordon mentioned, with the intent of submitting a pull request, but I think it will be easier to work on this once other pull requests are merged.
