### ISSUE TITLE
🚀💻 – document documentation workflow

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#137]
**Describe the feature you want and how it meets your needs or solves a problem**

As a spec contributor, I want documentation of the documentation workflow so that I can understand how to modify documentation.

**Describe the solution you'd like**

I think we should add a documentation workflow description to the `CONTRIBUTING.md` file. It should contain the relationship among `mkdocs.yml`, `main.py`, `requirements.txt`, the files in `docs`, and the workflows in `.github/workflows`.

**Describe alternatives you've considered**

**Additional context**

**Comment by jlstpaul** [comment]
Working on a piece of this now!

**Comment by jlstpaul** [comment]
I have created a Google document [here ](https://docs.google.com/document/d/1h2o-P6BGDrJD-9gIv7W7Jo3nmKJM46jfkcTaE0yW7cc/edit) to work out the structure and details of this content.  I have started this as a broader "Understanding TIDES and Frictionless" document, be we can take the pieces and use them elsewhere, like in CONTRIBUTING.md as Joey suggest.  

Please add details to how the documentation is generated.

I also have sections on how validation of the spec occurs, and how validation of data files will occur. Please feel free to add details there, too.
