### ISSUE TITLE
🐛📄 – more fully define relationship between reference schedule and `trips_performed`

### ISSUE THREAD

**Issue by jlstpaul** [TIDES-transit/TIDES#138]
**Describe the problem**
There is still confusion on how `trips_performed` is populated depending on different scenarios and relationships to the reference schedule.
 
**Possible Solutions**
Details are below, but it in summary, I am recommending to

- [ ] Modify the enum for `schedule_relationship` and potentially add a new field to more fully reflect both the relationship of the trip to the schedule and what happened to the scheduled trip

- [ ] Rename the `service_status` field and modify the enum to more clearly reflect the meaning of the field and the potential values

 
**Additional context**
 
There are three pieces of information that are needed to more fully define the relationship between the reference schedule and `trips_performed`
 
- What is the relationship between this trip and the reference schedule (e.g., GTFS).  This is the existing `schedule_relationship` field
- What is relationship between the planned trip, whether it was the reference schedule or not, and what actually happened.
- What type of trip is this?  In-service, not-in service, etc.   
 
Looking at each of these in more detail:
 

**1. What is the relationship between this trip and the reference schedule (e.g., GTFS).**  

This is the existing field `schedule_relationship`.  The enum values seem to be based on GTFS-realtime, but don't match exactly.  
 
0 - Scheduled
1 - Skipped
2 - Missing data
3 - Unscheduled
4 - Canceled
5 - Duplicated
6 - Schedule modified
 

> Reference: [GTFS-realtime schedule relationship enum](https://developers.google.com/transit/gtfs-realtime/reference#enum-schedulerelationship-2)
>  
> •	SCHEDULED        - Trip that is running in accordance with its GTFS schedule, or is close enough to the scheduled trip to be associated with it.
> •	ADDED - An extra trip that was added in addition to a running schedule, for example, to replace a broken vehicle or to respond to sudden passenger load.
> •	UNSCHEDULED - A trip that is running with no schedule associated to it - this value is used to identify trips defined in GTFS frequencies.txt with exact_times = 0. It should not be used to describe trips not defined in GTFS frequencies.txt, or trips in GTFS frequencies.txt with exact_times = 1.
> •	CANCELED - A trip that existed in the schedule but was removed.

 
**2. What is relationship between the planned trip, whether it was the reference schedule or not, and what actually happened.**
 
There is not currently a separate field for this.   The possible values we have discussed in [this document](https://docs.google.com/spreadsheets/d/1I038V5FUR_NiAnoVxpfZjWixmig67fhygFEf98gO8RE/edit#gid=0) include
 
•	The scheduled trip ran, and there is data for it
•	The scheduled trip ran, but there is no data for it
•	The scheduled trip was canceled
•	The scheduled trip ran, but only partially
•	More than one vehicle operated all or part of the scheduled trip 
•	The trip ran as added service (not  in the schedule)
 
Do we need to add a field for this?  Or is it okay to combine this information into the `schedule_relationship` field.
 
**3. What type of trip is this?  In-service, not-in service, etc.**
 
This was the intent of the `in_service` field (from the TCRP report) and now called `service_status`
 
The current enum values are:
- In passenger service
- En-route to service
- Traveling from a service trip
- On a layover
- Returning to a garage due to a suspension or breakdown
- Travel for on-route replacement of breakdown
- Other not in service
 
I would suggest renaming this to `service_type` and using the following enums
•	In-service
•	Not-in service - enroute to start of service (pullout)
•	Not-in service - enroute from end of service (pullin)
•	Not-in service - enroute to start of service, to replace breakdown (pullout)
•	Not-in service - enroute from end of service, due to breakdown or suspension (pullin)
•	Not-in service - traveling between trips (deadhead) 
•	Not-in service - traveling to layover location from end of trip (deadhead)
•	Not-in service - traveling from layover location to start of trip (deadhead)
•	Not-in service - other 
•	On a layover
 
Note that this also introduces the complication that there may be multiple reference schedules, say a GTFS dataset for in-service trips and an ODS dataset for not-in service trips.  When there is a `trip_id_scheduled` value for a `trips_performed` record, how do I know which fileset the trip comes from?  Perhaps this is a separate issue.

**Comment by jlstpaul** [comment]
I propose to remove `service_status`

I propose to create a new field called `service_type`, a `string` value that would *indicate the type of service provided by the trip*. 

It would have the following values:

- **IN SERVICE** = In-service trip
- **PULLOUT** = Not-in service - enroute to start of service
- **PULLIN** =  Not-in service - enroute from end of service
- **EXTRA PULLOUT** = Not-in service - enroute to start of service, to replace breakdown
- **EXTRA PULLIN** = Not-in service - enroute from end of service, due to breakdown or suspension
- **DEADHEAD** = Not-in service - traveling between trips   _Note: This value may also be used to represent any other Not-in service trip if they are not differentiated_.
- **DEADHEAD TO LAYOVER** = Not-in service - traveling to layover location from end of trip
- **DEADHEAD FROM LAYOVER** = Not-in service - traveling from layover location to start of trip
- **NOT IN SERVICE** = Not-in service - other
- **LAYOVER**	= On a layover _(would be unlikely to be used, since layovers are not generally represented as trips, but this would allow that if desired)_

**Comment by gabriel-korbato** [comment]
Maybe `movement_type` would be better than `service_type`, because without context the latter could be interpreted as bus/train or normal/express, etc.  We could also consider having a boolean `revenue` (true or false), and then an optional `deadhead_type` field that is null if `revenue` is true and can take any of the following values otherwise: PULLOUT, PULLIN, EXTRA PULLOUT, EXTRA PULLIN, TO LAYOVER, FROM LAYOVER, LAYOVER, OTHER.

**Comment by jlstpaul** [comment]
I like the suggestion from @gabriel-korbato to separate `service_type` into two fields: `in_service` as a required boolean and `deadhead_type` as an optional string.  This also helps address the issue of identifying which schedule data set to use from #151 

This same solution should be applied to the `trips_performed` and `vehicle_location_event` (`in_service` field) tables.

**Comment by jlstpaul** [comment]
Barring further comment, here is my proposal for this issue and #139 

- `trips_performed`
  - remove `service_status` field

  - add `in_service` as a Boolean
    - TRUE if the trip is in_service
    - FALSE if the trips is pull, deadhead, etc.
 
  - add `deadhead_type` as a String
    -  PULLOUT = Not-in service - enroute to start of service
    -  PULLIN = Not-in service - enroute from end of service
    -  EXTRA PULLOUT = Not-in service - enroute to start of service, to replace breakdown
    -  EXTRA PULLIN = Not-in service - enroute from end of service, due to breakdown or suspension
    -  DEADHEAD = Not-in service - traveling between trips Note: This value may also be used to represent any other Not-in service trip if they are not differentiated.
    -  DEADHEAD TO LAYOVER = Not-in service - traveling to layover location from end of trip
    -  DEADHEAD FROM LAYOVER = Not-in service - traveling from layover location to start of trip
    -  NOT IN SERVICE = Not-in service - other
    -  LAYOVER = On a layover (would be unlikely to be used, since layovers are not generally represented as trips, but this would allow that if desired)

- `stops_visited`

  - modify values for `schedule_relationship` to 
    - **SCHEDULED** = Vehicle operating scheduled trip (or a copied trip) stopped at a scheduled location. Associated with trips_performed.schedule_relationship values of SCHEDULED, PLANNED, MODIFIED, or DUPLICATED. Matches use of SCHEDULED in GTFS-realtime.
    - **SKIPPED** = Vehicle operating scheduled service passed by but did not stop at the scheduled location. Associated with trips_performed.schedule_relationship value of SCHEDULED.
    - **ADDED** = Vehicle operating either scheduled or added service stopped at an unscheduled location. Associated with trips_performed.schedule_relationship values of SCHEDULED, ADDED, or MODIFIED
    - **MISSING** = Vehicle operated a trip, but there is no data for this stop. This would be used when we know the trip was operated. May be associated with any value of trips_performed.schedule_relationship, including a value of MISSING for the trip.

- `vehicle_locations`
  - modify `in_service` to be a Boolean
    - TRUE if the trip is in_service
    - FALSE if the trips is pull, deadhead, etc.
  
  - add `deadhead_type` as a String with the same values as `trips_performed.deadhead_type` above

  - modify values for `schedule_relationship` to 
    - **SCHEDULED** = Vehicle operating scheduled trip (or a copied trip) stopped at a scheduled location. Associated with trips_performed.schedule_relationship values of SCHEDULED, PLANNED, MODIFIED, or DUPLICATED. Matches use of SCHEDULED in GTFS-realtime.
    - **SKIPPED** = Vehicle operating scheduled service passed by but did not stop at the scheduled location. Associated with trips_performed.schedule_relationship value of SCHEDULED.
    - **ADDED** = Vehicle operating either scheduled or added service stopped at an unscheduled location. Associated with trips_performed.schedule_relationship values of SCHEDULED, ADDED, or MODIFIED
    - **MISSING** = Vehicle operated a trip, but there is no data for this stop. This would be used when we know the trip was operated. May be associated with any value of trips_performed.schedule_relationship, including a value of MISSING for the trip.

**Comment by jlstpaul** [comment]
Per conversation during the Contributor Meeting today, update the above recommendation as follows:

- `trips_performed`
  - rename `service_status` to `trip_type`, allow the following values
    -  IN SERVICE = In revenue/passenger service
    -  DEADHEAD = Not-in service - traveling between trips Note: This value may also be used to represent any other Not-in service trip if they are not differentiated.
    -  LAYOVER = On a layover 
    -  PULLOUT = Not-in service - enroute to start of service
    -  PULLIN = Not-in service - enroute from end of service
    -  EXTRA PULLOUT = Not-in service - enroute to start of service, to replace breakdown
    -  EXTRA PULLIN = Not-in service - enroute from end of service, due to breakdown or suspension

    -  DEADHEAD TO LAYOVER = Not-in service - traveling to layover location from end of trip
    -  DEADHEAD FROM LAYOVER = Not-in service - traveling from layover location to start of trip
    -  NOT IN SERVICE = Not-in service - other


- `vehicle_locations`

  - rename `in_service` to `trip_type` as a String with the same values as `trips_performed.trip_type` above

**Comment by jlstpaul** [comment]
Per the above comment, the value of LAYOVER for 'trips_performed.trip_type` and 'vehicle_locations.trip_type` would allow TIDES data to explicitly define a `trips_performed` record to represent the layover in between trips.  This would not be required.  

The benefits of this are
- allow for `vehicle_locations` event records that occur during a layover to be linked to a `trips_performed` record.
- allow for aggregation of actual vehicle hours and miles data to more explicitly generated from `trips_performed` records (for example to support NTD reporting).

Since GTFS and ODS do not define layovers and trips and AVL system don't generall report layovers as trips, creating `trips_performed` records for layovesr would require additional logic within the data loading scripts.

**Comment by gabriel-korbato** [comment]
@jlstpaul Looks good and it should be straightforward to make the change.  Do we need DEADHEAD TO LAYOVER and DEADHEAD FROM LAYOVER?  Wouldn't those movements be separated into a DEADHEAD trip and a LAYOVER trip?  And you could look at the succession of movements if you care to know whether a deadhead was to/from a layover or something else?

**Comment by jlstpaul** [comment]
The reason for DEADHEAD TO/FROM LAYOVER is to represent the following scheduled operational situation:

Bus arrives at end of trip.  Bus deadheads to a layover location that is located away from the terminal.  Bus lays over. Bus deadheads to the location for the start of the next trip.  

These could be just DEADHEAD trips, but they tend to be very short, sometimes skipped, etc.  So representing them differently allows that to be managed without needing to look at the adjacent trips.  That being said, I'm not certain they would be needed or used.

**Comment by gabriel-korbato** [comment]
I'm good either way, but I did want to point that out because those two stand out by labeling the trip in question and also saying something about the next or previous trip.  Whatever your choice is will be fine.

**Comment by KatrinaMKaiser** [comment]
Closed in pr #167
