### ISSUE TITLE
🐛📄 – more fully define the relationship between `stops_visited` and the reference schedule

### ISSUE THREAD

**Issue by jlstpaul** [TIDES-transit/TIDES#139]
**Describe the problem**

The meaning of the enum values for  the `schedule_relationship` field in `stops_visited` table are not clear

**Possible Solutions**

More fully document the meaning of each of the values of `stops_visited.schedule_relationship` and/or
Add an additional field to help convey a) relationship to the schedule, and b) what happened in the operation of the service w/r/t the scheduled stop

**Additional context**

The `schedule_relationship` field appears to be intended to convey two pieces of information
•	Was the stop referenced in the original schedule, and
•	Did  the bus serve the stop (for passenger activity), just pass by the stop, or never come near the stop

There is general agreement that there should only be a `stop_visited` record when a vehicle actual goes past a stop.  If the trip is not operators of if the vehicle never gets to the stop, then there will not be a record.  

`schedule_relationship` has current values of

- Scheduled
- Skipped
- Missing data
- Unscheduled
- Canceled
- Duplicated
- Schedule modified

The documentation for the field reference the `schedule_relationship` enum in GTFS-realtime which has the following values  ([reference](https://gtfs.org/realtime/reference/#enum-schedulerelationship))
- SCHEDULED
- SKIPPED
- NO_DATA
- UNSCHEDULED

**Comment by jlstpaul** [comment]
I proposed the following values for `stops_visited.schedule_relationship`

- **SCHEDULED** = Vehicle operating scheduled trip (or a copied trip) stopped at a scheduled location.  Associated with `trips_performed.schedule_relationship`  values of SCHEDULED, PLANNED, MODIFIED, or DUPLICATED.  Matches use of SCHEDULED in GTFS-realtime.

- **UNSCHEDULED** = Vehicle operating frequency-based service stopped at planned location. Associated with `trips_performed.schedule_relationship` value of UNSCHEDULED.

- **SKIPPED** = Vehicle operating scheduled service passed by but did not stop at the scheduled location. Associated with `trips_performed.schedule_relationship` value of SCHEDULED.
 
- **ADDED** = Vehicle operating either scheduled or added service stopped at an unscheduled location.  Associated with `trips_performed.schedule_relationship` values of SCHEDULED, ADDED, or MODIFIED

- **MISSING** = Vehicle operated a trip, but there is no data for this stop.  This would be used when we know the trip was operated. May be associated with any value of `trips_performed.schedule_relationship`, including a value of MISSING for the trip.

Note that `trips_peformed` records with `schedule_relationship` values of CANCELED, SKIPPED, or DELETED would be presumed not to have any associated `stops_visited` records since the trip did not operate.

**Comment by jlstpaul** [comment]
Per discussion, do  not need UNSCHEDULED here. Can rely on status of `trips_performed`.

**Comment by tsherlockcraig** [comment]
Including the last revision (elimination of UNSCHEDULED from 'stops_visited.schedule_relationship', these look good to me. I appreciate the SKIPPED/MISSING being both maintained and more clearly defined.

**Comment by jlstpaul** [comment]
To complicate this a little more, there is also the `vehicle_locations.schedule_relationship` field.  It currently has the following values and is intended to reference [GTFS-realtime](https://gtfs.org/realtime/reference/#enum-schedulerelationship).  

- **SCHEDULED**
- **SKIPPED**
- **NO DATA**
- **UNSCHEDULED**

This is intended to be used when the `vehicle_locations` event represents the vehicle serving or passing by a stop. 

Should we:

- Option 1: Leave this as is, to facilitate transfer of data from a GTFS-realtime feed

- Option 2: Adjust the values to more closely match the proposal for `stops_visited.schedule_relationship`
  - replace **NO DATA** with **MISSING**
  - eliminate **UNSCHEDULED** (and translate this to **SCHEDULED**)
  - add **ADDED** 

My preference is Option 2, so that `vehicle_locations` and `stops_visited` match each other.   This would then require the data transfer process that creates `vehicle_locations` records to do the necessary translation from GTFS-realtime if that is the data source.

**Comment by jlstpaul** [comment]
See [this comment](https://github.com/TIDES-transit/TIDES/issues/138#issuecomment-1648665501) on #138  as the proposed resolution here.

**Comment by KatrinaMKaiser** [comment]
Closed in pr #167
