### ISSUE TITLE
🐛💻 – build-deploy job in docs workflow is skipped on main branch

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#168]
**Describe the problem**

[This line](https://github.com/TIDES-transit/TIDES/blob/2d4c7ea845d690337e1075af5cd53a8b09cbaf8c/.github/workflows/docs.yml#L14) seems to limit this workflow to running on pull-requests, as a result, the [last successful documentation build](https://github.com/TIDES-transit/TIDES/actions/runs/5556514453) on `main` was July 14th.

**Steps to reproduce**

Merge any branch into main or manually trigger the workflow, it will be skipped.

**Comment by botanize** [comment]
@SorenSpicknall, after removing the line the documentation builds on main as expected, but we may need to find a new way to address the original issue. I thought there was a way to require workflow approvals for outside forks, or maybe the pull_request_target event is the key?

**Comment by botanize** [comment]
Could use the `permissions` key to grant write access to the PR itself, even when running on a fork.
```yaml
permissions:
      pull-requests: write
```

**Comment by botanize** [comment]
Could also tweak the conditions in the `if` clause I just removed, return true if the event is anything other than 'pull_request', and check that the repo is this repo if 'pull_request'.

**Comment by SorenSpicknall** [comment]
> Could also tweak the conditions in the `if` clause I just removed, return true if the event is anything other than 'pull_request', and check that the repo is this repo if 'pull_request'. Maybe:
> 
> `if: ${{ github.event_name != "pull_request" | github.event.pull_request.head.repo.full_name == github.repository }}`

Something like this is my preferred option, I think. I'd prefer not to grant write permissions on the PR because of security risks associated with forks. Thank you for continuing to iterate on this!
