### ISSUE TITLE
🐛💻 – Modify CONTRIBUTING,md to be consistent with updated governance and change management documents

### ISSUE THREAD

**Issue by jlstpaul** [TIDES-transit/TIDES#175]
The sections in READEME.md on Project Governance and Review and Approval Process are not consistent with the new content in the Governance document and the planned content for the Versioning + Change Management document. 

The  two sections should be revised and should reference the new documents.

**Comment by e-lo** [comment]
>The sections in READEME.md on Project Governance and Review 

I think you mean the section in `CONTRIBUTING.md`? Just want to make sure I hadn't missed something in `README.md` before I submit a PR

**Comment by jlstpaul** [comment]
> I think you mean the section in CONTRIBUTING.md? Just want to make sure I hadn't missed something in README.md before I submit a PR


Yes! Doing too many things at once.
