### ISSUE TITLE
🧹 Add basic branch protection rules

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#182]
Add branch protection rules including:
 - Require PRs to commit to `main`
 - Require review from CODEOWNERS
 - Dismiss a pull request approval review when a code-modifying commit 

To support:
- add CODEOWNERS file to `/spec`  with TIDES Board and Program Manager

FYI @jlstpaul

**Comment by e-lo** [comment]
added the rules but need to add CODEOWNERS if/when @jlstpaul agrees with the lis in #183

**Comment by botanize** [comment]
If CODEOWNERS is all contributors, then it takes only one contributor approval to merge a pull-request, correct? This seems like a departure from relying mostly on the PMT to approve pull-requests. Do we want to continue to require some level of approval from the Board? Or a minimum number of approvals? Or a voting process?

**Comment by e-lo** [comment]
I think we want to differentiate between normative changes to spec (things
in spec folder, where we can have the board be the codeowner) and code and
documentation updates
