### ISSUE TITLE
🧹 Update Github Teams  to be consistent with Fall 2023 Governance

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#183]
Realign our Github Teams to be consistent with the  [updated governance](https://tides-transit.github.io/TIDES/main/governance/)

Teams:

- [Board](#tides-board)
- [Program Manager](#program-manager)
- [Contributors](#contributors)

##  TIDES Board

**Who:** TIDES Board
**What can they do per governance?** Anything

Suggested Organization Role: [owner](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization)
Suggested Repo Team: [Admin](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)

NOTE: Admin Team can also override branch protection rules if necessary for writing to `main`

## Program Manager

**Who:** Program Manager 
**What can they do per governance?** Anything

Suggested Organization Role: [member](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization) + "team maintainer" privileges
Suggested Repo Team: [Admin](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)

NOTE: Admin Team can also override branch protection rules if necessary for writing to `main`

## Contributors

**Who:** All registered TIDES Contributors
**What can they do per governance?** create issues, discussions, and pull requests in the TIDES repository

Suggested Organization Role: [member](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization)
Suggested Repo Team: [Write](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)

NOTE: this is more access than is strictly defined in the governance. I think this is ok so long as we have branch-protection rules for `main` (just implemented) so that not too much damage can be done.

**Comment by e-lo** [comment]
@jlstpaul please review and if you are in agreement I can implement...

**Comment by jlstpaul** [comment]
Yes. Please implement! Thank you!

**Comment by e-lo** [comment]
Implementation in `tides-transit` organization:
<img width="420" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/123cbc9c-3c50-466d-8f1b-1a16ee6aec9c">

Implementation in `TIDES` repository:
<img width="867" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/e71eda25-618b-4167-9f40-00d9c42791c5">
