### ISSUE TITLE
🗳️   Approve Change Management Policy 

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#184]
[Draft available for comment.](https://docs.google.com/document/d/1kEJHIGv5YWeZa13iWWtdcNooPxhZQ42kwTwEhrZbrTM/edit)

Steps:
- [x] Post draft for discussion
- [x] TIDES Board notes approval @jlstpaul
- [ ] Add as the TIDES Versioning Policy to [`/docs/governance/artifacts`](https://docs.google.com/document/d/1kEJHIGv5YWeZa13iWWtdcNooPxhZQ42kwTwEhrZbrTM/edit)

**Comment by jlstpaul** [comment]
The TIDES Change Management Policy was approved on November 28.
