### ISSUE TITLE
🎈 Get an initial logo to use for TIDES

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#185]
A non-essential but potentially fun issue to take on...

For use in:
- documentation header
- favicon

In order to...
- easily recognize that I'm looking at TIDES documentation and not all the other mkdocs sites
- look put together 🎸

**Comment by e-lo** [comment]
DALL-E's initial go at it was horrible...amusingly so.  Will try more prompt details.
<img width="319" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/41670713-20b5-4ef3-9b0b-69dca3c2ec46">

**Comment by e-lo** [comment]
...now it is thinking in morse code? 
<img width="239" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/a1d845c0-7230-4b91-90a3-2af0f315a3d1">

**Comment by jlstpaul** [comment]
I've always liked this header that I took (without attribution) from somewhere years ago....

![Tides header](https://github.com/TIDES-transit/TIDES/assets/5291685/febca9cc-701d-4b0e-ba58-42fa065c9830)

**Comment by e-lo** [comment]
turns out graphic designers still have some job security 😆 
<img width="300" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/09f3c4a1-9c6d-4bab-8ced-e68751392bfb">
