### ISSUE TITLE
🐛💻 – Implementation Challenges: Foreign Key Issues and Style Inconsistencies

### ISSUE THREAD

**Issue by Danishswag** [TIDES-transit/TIDES#187]
**Describe the problem**
After seeing TIDES had hit v1-dev, I tried implementing a full TIDES schema in our Oracle database and ran into a few inconsistencies/issues (mostly around foreign_keys):

**Bugs**

1. The primary key for `trips_performed` is `service_date` and `trip_id_performed`. Most foreign keys on `trip_id_performed` don't reference `service_date`, which is an issue for databases that require a Foreign Key to be a Primary Key in the reference table (Oracle and Postgres both require this at least).
   1. Could be fixed by adding `service_date` to the trip ID performed foreign key for any table where it exists.
   2. This includes `fare_transactions`, `passenger_events`, `stop_visits`, `vehicle_locations`
2. In `passenger_events`, the foreign key on `train_car_id` references a `train_car` table instead of `train_cars`
3. In `passenger_events`, the `stop_times` foreign key references `scheduled_stop_sequence` in `passenger_events`, but `stop_sequence` in `stop_times`. I think this should reference `stop_visits` instead of `stop_times`, and should reference `stop_sequence` in both tables instead?
4. In `stop_visits`, I wasn't quite sure what the the `scheduled_stop_sequence` foreign key was meant to account for, but both Oracle and Postgres break with the current setup. I think we'd have to make the foreign key match on `scheduled_trip_id` and a `service_date`/`schedule_date` as well? We don't include `scheduled_trip_id` in this table, personally I would recommend removing the foreign key and keeping the constraint at just > 0.

**Style**

1. The options in the enum for `device_type` all start with lower-case letters, while the first letter is capitalized in all other enums in TIDES. This doesn't really matter for usage, but it stood out to me.
  
2. The `vehicles` table has `capacity_bike`, `capacity_seated`, and `capacity_standing`, but has `wheelchair_capacity`. In `train_cars`, it has `capacity_seated`, `capacity_standing`, `bike_capacity`, and `wheelchair_capacity`
    1. It may be too late, but I would personally love to change `bike_capacity` to `capacity_bike` in `train_cars`. Could also consider changing `wheelchair_capacity` to `capacity_wheelchair` in both tables, but that's less noticeable since it's consistent.

**Steps to reproduce**
I would be happy to share all the PLSQL DDL I put together to create the tables, but I don't think it's possible to make minimally reproducible without access to an Oracle database.

**Comment by jlstpaul** [comment]
Thank you. These are excellent points.

**Bugs**
1. This can be corrected as suggested by adding `service_date` to the four referenced tables
2. This can be corrected as suggested.
3. I think the foreign reference in `passenger_events` should be to `stop_visits.trip_stop_sequence`
4. I don't think we should have a foreign reference to `stop_times` at this point.  There are several other linkages to GTFS/schedule data that are not listed as foreign references.

**Styles**
1. The enums for `devices` should be modified to start with upper case
2. I think we should change them all to `capacity_xxxx`

@Danishswag Would you like to make a PR for these changes or have someone else do that?

**Comment by Danishswag** [comment]
Yep! I can go ahead and make the PR today or tomorrow
