### ISSUE TITLE
🗳️ Approve additional TIDES-Board Members

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#189]
The current TIDES Board has indicated a desire to expand the board to five seats by the time TIDES Project Management duties have been transferred (see #188 )

Progress:

- [x] Identify and get agreement for four additional members
- [ ] Publicize a vote decision for the addition of these members and the start of their term
- [ ] Record this decision in `/docs/governance/artifacts`
- [x] Update GitHub privileges
- [ ] Update documentation

**Comment by jlstpaul** [comment]
Here is the official announcement to expand the board (for the governance artifacts) 
[board expansion announcement 2023-11-29.pdf](https://github.com/TIDES-transit/TIDES/files/13507761/board.expansion.announcement.2023-11-29.pdf)

**Comment by e-lo** [comment]
will add once @jlstpaul approves #192 which updates how policies and board actions are displayed
