### ISSUE TITLE
📘 Change Management Policy Format

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#195]
As a ___ I'd like to ____ so that ____

Per @jlstpaul 's approval of #192 , he would like to discuss the format of the Change Management Policy.

Background:

- Policy was originally approved as a google doc
- @e-lo translated to a markdown document so it was viewable and formatted as a webpage

Thoughts:

- Where is source of truth on policies?
- If in markdown, do we provide link to rendered PDF (i.e. [using a plugin)](https://timvink.github.io/mkdocs-print-site-plugin/index.html)
- If google docs, do we just link to that from website?
- If PDF, how can we make sure content is searchable/available/linkable within existing documentation?

**Comment by botanize** [comment]
I'm in favor of the website being the source of truth (i.e., the markdown document). I see Google docs or other tools as aids in rapid collaboration when Git isn't appropriate, but the end result, the source of truth should remain the material committed to the repo. Is there a need for a PDF?

**Comment by jlstpaul** [comment]
My concern had more to do with the formatting within the markdown document. I concur with using markdown docs on GitHub as the source of truth.  I am going to close this issue for now.  We can come back to it later if needed.
