### ISSUE TITLE
🚀💻  Update CNAME to tides-transit.org

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#199]
**Describe the feature you want and how it meets your needs or solves a problem**

As a user interested in finding the TIDES documentation, I want it to have an easy-to-remember website like tides-transit.org so that I don't have to fuddle around with github orgs/repo names in a URL.

**Describe the solution you'd like**
Add tides-transit.org as CNAME

**Additional context**

- @themightychris has already procured the site
- Just need to set up CNAME and settings in github repo

**Comment by jlstpaul** [comment]
Thank you for this!

**Comment by e-lo** [comment]
thanks @themightychris!

Tides-transit.org is now live and https enforced...woot!

<img width="296" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/011993a9-39a9-4f1d-8855-13057845675b">
