### ISSUE TITLE
🚀💻 – Remove stale branches with a github action

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#200]
As a developer, I'd like stale branches to be removed regularly so that the branch lists and documentation list isn't so enormous to navigate.

**Comment by e-lo** [comment]
I just removed manually and it was fine. Closing this for now and the attached PR.

**Comment by jlstpaul** [comment]
@e-lo Thank you for removing the GitHub branches.  It looks like the Pages site still has copies of the test documentation from those. Is there an easy way to prune those too?
