### ISSUE TITLE
🚀 💻  – Backbone docs website infra (i.e. mkdocs with mike created with a GH workflow hosted on GH pages)

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#23]
As a stakeholder, I'd like to have human-readable documentation on the data standards which are available for various versions of the specification.

As a maintainer, I'd like the documentation to be as automagically created as possible.

## Possible Implementation

Mike w/ MkDocs

**Comment by botanize** [comment]
I configured pages for this repo, but the docs are available at <https://tides-transit.github.io/TIDES/main> instead of <https://tides-transit.github.io/TIDES>. Is this a `mike` configuration issue or expected behavior?

**Comment by botanize** [comment]
I had an idea, the current documentation workflow generates docs on every push, but, we could

- restrict to pushes to main or pull-requests to main
- and, restrict to just paths used for the documentation, but would have to maintain that list within the docs.yml workflow
- using `github.refname` as the version means that there will be a version for every branch in the repo, and that versions will have names like "main", "jpr_workflows", etc. Maybe we could use the date as the version name, e.g., (untested) `mike deploy --push --rebase "$(date '+%Y-%m-%d')"`

**Comment by e-lo** [comment]
Actually we can set the default in mike to main...standby

**Comment by e-lo** [comment]
Re:

> the current documentation workflow generates docs on every push

I think this is the behavior we want for now.  It allows us to review PRs, etc.

We can also set up aliases for things like latest-official, release-candidate, etc.

**Comment by e-lo** [comment]
@botanize and @jlstpaul I think we can close this?
