### ISSUE TITLE
Update issue tags based on what we need.

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#24]
As a product manager or contributor, I'd like to be able to view issues based on priority and my ability to help move them along.

**Comment by e-lo** [comment]
Per @botanize 's commennts in https://github.com/TIDES-transit/TIDES/pull/29, suggest having:

- `📄 spec`: pertains to the specification itself
- `💻 code`: pertains to the infrastructure code
- `📙 docs`: pertains to elaborating/updating the documentation...inline or otherwise
- `🚀 feature`: adds a new feature (to spec or code)
- `🐛 bug`: something's wrong  (in spec or code)
- `🧹 chore`: things like this...
- `❓ question`: a question

**Comment by botanize** [comment]
Will need to update the `labels` fields of the ISSUE_TEMPLATES files #29 (to add the emoji)

**Comment by e-lo** [comment]
No responses from @j-meelah or @jlstpaul so I'll take the 👍 from @botanize as approval to implement and will update the issue template PR to reflect.
