### ISSUE TITLE
Document contribution guidelines

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#3]
As a potential contributor, I need to understand:

- [ ] 1. Process for making contributions
      - [ ] a. practices for creating issues including required information as dictated by templates
      - [ ] b. practices for creating pull-requests including required information as dictated by templates
      - [ ] c. branching approach
      - [ ] d. style guide and any auto-enforcement practices of it (i.e. pre-commit check on PRs, etc)
      - [ ] d. testing approach and requirements
- [x] 2. Who is responsible for what (i.e. teams and their various privileges )
- [x] 3. Any agreements I need to sign, or contributor licensing agreements

**Comment by botanize** [comment]
As a potential contributor I also like to know,

- [ ] practices for creating issues (search for existing, 1  and only 1 issue per issue, markdown formatting, user story template, motivating example data)
- [ ] process for pull-requests, should I open an issue first? Approval/voting process, &c.
- [ ] templates for issues and pull-requests

**Comment by botanize** [comment]
A couple more:

- [ ] style guide
- [ ] .editorconfig file?

**Comment by e-lo** [comment]
Will add the above as details under other bullets (which are general)

**Comment by e-lo** [comment]
I'm also going to create separate issues for repo infra...this is for the instructions.
