### ISSUE TITLE
🐛 📄 – timestamp fields of type `time` don't support >24 hour clocks

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#31]
I need to be able to represent a service date and time like, date: "2022-08-26", time: "24:30:00", or datetime: "2022-08-26 24:30:00", but the frictionless `time` and `datetime` types don't allow that.

## Context
The R [frictionless](https://github.com/frictionlessdata/frictionless-r) package simply removes the time component from `datetime` types that are beyond 24 hours, e.g., '2022-08-26 24:30:00' -> '2022-08-26 00:00:00', and errors on `time` types that are greater than '24:00:00'.  Similarly, the Python [frictionless](https://github.com/frictionlessdata/frictionless-py) package will throw `dateutil.parser._parser.ParserError: hour must be in 0..23: 2022-08-26 24:30:00`.

Many agencies operate service days longer than 24 hours, for example, Metro Transit uses a 28 hour clock. This results in a service date that may not match the calendar date, e.g., a trip operating from 2022-08-26 23:45:00 to 2022-08-27 00:30:00 is all part of the 2022-08-26 service date, but spans the 2022-08-26 and 2022-08-27 calendar dates. In GTFS these times are represented as >24 hours. In this example, the scheduled time of 00:30:00 on 2022-08-27 would be "24:30:00".

The frictionless `datetime` and `time` types however are [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), which is explicitly a 24 hour clock. So the combination of `date` (type = date) and `timestamp` (type = time) fields can not correctly identify the time on the service date. 

For example, for service date 2022-08-26 (Weekday) a trip that starts at 23:45:00 and ends at 24:30:00 can not be correctly identified if the `actual_arrival_time` field is of type `time` because you'd have to choose between having a date + timestamp combination that resulted in a correct calendar time (date: 2022-08-27, timestamp: 00:30:00) vs having the correct service date, but the wrong calendar time (date: 2022-08-26, timestamp: 00:30:00).

## Options

1. Use `datetime` as the type for all time fields that are associated with a service date (date<date>: 2022-08-26, timestamp<datetime>: 2022-08-27 00:30:00). This is a little verbose, but it would be easy for systems to convert service date + time in service day to datetime. For systems without a concept of service date, the `date` and `timestamp` fields would be redundant.
2. Use `integer` as the type for all time fields that are associated with a service date (date<date>: 2022-08-26, time<integer>: 88200). This would be the number of seconds into the service date, e.g., 24:30:00 = 88200. This is often the native timestamp format for systems that use service days, for systems without service days the timestamp could easily be broken down into date + integer time fields. Integer time, while easy for our machine overlords, is not human friendly.
3. Use `string` as the type and `%H:%M:%S` as the format for all time fields that are associated with a service date, same as GTFS (date<date>: 2022-08-26, time<string>: "24:30:00"). This would allow times like 24:30:00 that are not allowed by the ISO 8601 `time` type, and would prevent existing frictionless tools from throwing errors or returning incorrect times when parsing those times. But to turn these strings into times would require a custom parser that would probably end up converting the string to an integer time representation (which has been implemented numerous times for GTFS).

## Decision
Changes all `time` type fields to `datetime` types, and all instances of `time` in the field description to `timestamp`.

**Comment by AztecCyclocross** [comment]
I  like the idea of having two fields for all time data. One would be in human-readable format compliant with the ISO 8601 time standard, the second field would be in seconds past midnight format. This would allow values greater than 24 hours to be represented as values greater than 86400 seconds.

**Comment by AztecCyclocross** [comment]
I thought I would add some discussion as to why I like the solution I recommended above. 1) It is consistent with how times are recorded in GTFS, 2) It makes calculating differences in event times that span midnight much easier, and 3) It is easy to look at the human-readable time format in the adjacent column and immediately know whether 2am references 2am today or 2am tomorrow by simply looking to see that the seconds column is greater than 86400.

**Comment by gabriel-korbato** [comment]
It is best practice to represent actual events as date-time fields following ISO 8601, which unequivocally define when an event happened anywhere in the world, regardless of time zone or daylight savings.  I've seen many bugs in several systems and earlier versions of my code caused by representing actual times in other ways, so I would strongly suggest against changing the spec here.  I think this aligns with the first option, if I understand it correctly.  

The problem with the second and third options is that they specify a clock time rather than an event time.  That is fine for schedules because their events are repeated across days, but it's an issue especially with daylight savings and sometimes with time zones.  

At Korbato we use a service date such as `2022-09-28` for data organization and aggregation, and a timestamp such as `2022-09-28 16:41:13-04` to specify events.  We've had multiple frustrating issues with other schemes and not a single one with this one.
