### ISSUE TITLE
🐛💻 – edit this page links broken in gh-pages

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#63]
**Describe the problem**

The edit link for https://tides-transit.github.io/TIDES/main/tables/ is https://github.com/TIDES-transit/TIDES/edit/main/docs/tables.md, but, tables.md is generated by mkdocs/mike and only exists in the gh-pages branch of the repo.

Since these are built from the spec, templates, and some python code, it doesn't really make sense for these pages to have edit links. Editing is done through pull-requests. Can they be disabled for the whole site?

**Comment by e-lo** [comment]
I think that link is still right for editing. Since `main` branch is protected, editing it in the GitHub GUI would generate a PR from a fork to main, which would generate a new docs set when pulled into `main`.  Should we try it out to confirm? (or did you try this and then file this 🐛 ?)

**Comment by e-lo** [comment]
Actually - I'm working on a PR that will address this through templating and copying in the content from the main repo through macro plug-in rather than copying it in.  That should make the editing for those other pages actually work.

**Comment by botanize** [comment]
Edit links work! But they might be the wrong tool for the wrong people, see #83 .
