### ISSUE TITLE
Add licenses

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#7]
As a TIDES-Stakeholder, I need to know which license the TIDES data standards suite is licensed under in order to discern if it is appropriate for my use cases and if I should contribute to it.

**Comment by jlstpaul** [comment]
My instinct is to use the MIT license unless there is some objection.

**Comment by themightychris** [comment]
@jlstpaul my default used to be MIT, but best practice for permissive licenses seems to have shifted towards Apache2 being a better default.

Apache2 is essentially just as permissive, but make a few legal things more explicit that make it easier for institutions that have to care about managing legal risks to participate in using and publishing software under the license:

- making it explicit that if the author owns any patents covering the code, license to use the patents is granted too
- making it explicit that license to use any trademarks owned by the author is _not_ granted (e.g. someone using a Caltrans-published tool couldn't publish their own version with Caltrans' logo still included)
- Derivative works need to document for their users what they changed on top of the upstream project

**Comment by botanize** [comment]
That sounds good to me, it also matches GTFS spec licensing, which has a very similar set of use cases.
