### ISSUE TITLE
🐛📄 – trips_performed summary table can't be summarized from event tables

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#70]
**Describe the problem**

The trips_performed table contains `trip_id_scheduled` which is not in any of the event tables, so it can't be created by summarizing from event tables. 

**Possible Solutions**

Add `trip_id_scheduled` to the event tables wherever `trip_id_performed` exists.

**Additional context**

See discussion in #51 

- https://github.com/TIDES-transit/TIDES/issues/51#issuecomment-1262757286
- https://github.com/TIDES-transit/TIDES/issues/51#issuecomment-1262937151

**Comment by gabriel-korbato** [comment]
> **Possible Solutions**
> Add `trip_id_scheduled` to the event tables wherever `trip_id_performed` exists.

I like the idea of adding `trip_id_scheduled` to the `vehicle_locations` table as an optional field.  I don't think it has to be conditional on having `trip_id_performed`.

**Comment by botanize** [comment]
My bad, I didn't mean making `trip_id_scheduled` conditional on `trip_id_performed` just that it should be added as a field to any event table with `trip_id_performed`.

It's a bug and a feature!
