### ISSUE TITLE
🐛📄 – trip_id_performed should be optional in vehicle_locations 

### ISSUE THREAD

**Issue by gabriel-korbato** [TIDES-transit/TIDES#71]
**Describe the problem**
While true AVL systems generally keep track of trips and give then a unique ID, some transit agencies lack these AVL and instead have less expensive GPS fleet tracking units that simply provide a stream of vehicle location events, with vehicle or device ID, a timestamp, and lat/lon coordinates.  `trip_id_performed` is currently marked as required in `vehicle_locations`, so the spec doesn't currently support this use case.  

**Possible Solutions**
Make `trip_id_performed` optional in `vehicle_locations`.  

**Additional context**
Vehicle location heartbeat or breadcrumb data that lacks trips and stops would be processed by a model that would identify trips and stop visits, generating the summary files accordingly, and possibly generating a new version of `vehicle_locations` decorated with the synthesized `trip_id_performed`.

**Process Checklist**

- [x] **Issue Creation:** Fill in required portions of issue template
- [x] **Fact-finding:** Describe potential solutions and recommend one.
- [ ] **Example Updates:** Use samples of real ITS data, solicit samples from other providers and ITS systems.
- [ ] **Consensus:** Build consensus around a single solution.
- [ ] **Implementation:** Implement the change in a pull-request.
- [ ] **Completion:** Follow governance process for pull-request approval.

**Comment by botanize** [comment]
I'm so glad you filed this! We've had some discussions about this, and where the trip assignment should be performed. Here are a couple of ideas:

1. It's not TIDES unless it has trip_id_performed/scheduled, so the data producer is responsible for pre-processing to add trip_id.
2. This is a common enough problem that developing shared tools to process vehicle_locations to add trip and stop info would be a valuable addition to TIDES, and therefore the spec should be modified to allow that.

**Comment by gabriel-korbato** [comment]
At Korbato we have models for synthesizing trips and stop visits from just heartbeats, or to correct issues in stop-level AVL data using supplemental heartbeat data.  This a shared tool in the sense that it is shared across Korbato's agency customers, but not in the sense of being open-source.  Regardless, TIDES should allow this use case, as it really does happen often.

**Comment by e-lo** [comment]
1. Create an issue for the feature request (you're in the right place!)
2. Fact-finding: Describe potential solutions and recommend one.
  Use samples of real ITS data, solicit samples from other providers and ITS systems.
3. Build consensus around a single solution.
4. Implement the change in a pull-request.
5. Follow governance process for pull-request approval.

**Comment by Danishswag** [comment]
Since I dropped off early, could someone potentially drop a summary of what the working group came up with for a proposal on how/whether to include the trip ID in the vehicle locations spec?
