### ISSUE TITLE
🚀💻 – add contributors to contributors.md

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#74]
**Describe the feature you want and how it meets your needs or solves a problem**
I want to see who contributed to the project and reward them for their contributions by including them in the contributors.md file.

**Describe the solution you'd like**
Rust has a cool feature where you can see the [contributors and the number of contributions](https://thanks.rust-lang.org/) for each release and overall. https://github.com/rust-lang/thanks

There are many ways to format the contributors file. One option is the output of `git shortlog -sne`, which shows commit counts and works with a `.mailmap` file to fix email addresses and canonical names (see [gitmailmap](https://git-scm.com/docs/gitmailmap)).

```md
     8  Joey Reid <botanize@users.noreply.github.com>
     3  John Levin <jlstpaul@users.noreply.github.com>
     2  Elizabeth Sall <easall@gmail.com>
     2  j-meelah <jameelah.y@jarv.us>
```

This would be super easy to add to the `docs` workflow, so that contributors.md is updated on every pull-request into main. The major downside is that important forms of contribution other than commits (e.g., PR reviews, issue creation and discussion) wouldn't be recognized. 

However fun it is to see commit counts, they're not good measures of effort or importance. It is also easy to report just commit authors in alphabetical order `git log --format="%aN <%aE>" | sort | uniq`, e.g.,

```md
Elizabeth Sall <easall@gmail.com>
Joey Reid <botanize@users.noreply.github.com>
John Levin <jlstpaul@users.noreply.github.com>
j-meelah <jameelah.y@jarv.us>
```

**Alternative**
A different approach is the [all-contributors](https://allcontributors.org/) bot or CLI, which can be used to tag peoples contributions, whatever they are, and will create pull-requests to integrate those contributions into a markdown file (contributors.md). Instead of generating the contributors content automatically, from something intrinsic to the repo, it stores contributions in a dot file (.all-contributorsrc) in the repo and then formats that into markdown. This is a bit more hands-on, using the bot or cli, but makes it fairly easy to recognize many types of contributions.

**Comment by e-lo** [comment]
Another option, leveraging mkdocs is [mkdocs-git-authors-plugin](https://timvink.github.io/mkdocs-git-authors-plugin/)

**Comment by e-lo** [comment]
I am fine with any of the above options.

**Comment by botanize** [comment]
> Another option, leveraging mkdocs is [mkdocs-git-authors-plugin](https://timvink.github.io/mkdocs-git-authors-plugin/)

It looks like this plugin only counts contributions to the docs?

**Comment by e-lo** [comment]
Since our adopted definition of TIDES-Contributor in the [TIDES governance](https://tides-transit.github.io/TIDES/main/governance/#tides-contributor) is not necessarily tied to **content contribution** but instead a registration process, I went ahead and added all the officially registered TIDES Contributors to `contributors.md` in the merged [PR for governance docs](https://github.com/TIDES-transit/TIDES/pull/177).

Per that definition, I think this issue could be closed but will leave that decision to @jlstpaul

**Comment by jlstpaul** [comment]
Agreed.  For now, I am happy to just list all those who are registered as Contributors.   Thank you for the PR for that @e-lo 

As an aside, I think we should ask the TIDES Manager to review the list of Contributors from time to time and potentially remove those who are inactive and agree to be removed.    But we do not need to address that now.

I also think in the future we could identify which aspects of the project individual contributors are most connected to, if that would be of value.
