### ISSUE TITLE
🐛📄 – Some fields in the TIDES spec clash with Protected Keywords in SQL Databases

### ISSUE THREAD

**Issue by Danishswag** [TIDES-transit/TIDES#82]
**Describe the problem**
While starting to sketch out the development of new data tables to store data that complies with the TIDES spec, we noticed several of the column names clash with protected SQL keywords. One example is in `vehicle_locations.schema.json`, where the service date column is named `date`, which is protected in most relational databases.

**Possible Solutions**

* Define a standard for changing the name of reserved words (e.g. `date` becomes `dt` instead when it is a field name) or require more detail in proposed field names (e.g. `date` becomes `service_date` in `vehicle_locations.schema.json`)
* Adjust the CONTRIBUTING.md file to specify part of the code review process will check against reserved words in common SQL databases
* Instead, could accept that the spec includes protected keywords (since it would be difficult to create a list of even the more common programming languages beyond just SQL), and put the onus on data owners and tool creators to define required workarounds.

**Additional context**
Here is a list of reserved keywords from most major database systems that could potentially serve as a filter for the new spec: [Drupal - List of SQL Reserved Words](https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words)

**Comment by botanize** [comment]
Hi, thanks for creating this issue. I think that the third solution you offer is probably the most appropriate. I think it's a source of confusion, or maybe just hasn't been settled, but the spec doesn't define database schema, and consumers are not required to use databases. MySQL and others allow you to either quote identifiers that are reserved keywords, or use qualified names, e.g., 

```sql
SELECT `date` FROM VehicleLocations
SELECT VehicleLocations.date FROM VehicleLocations
```

That said, I think there is value in using more descriptive names, like `service_date` in place of `date` and `event_timestamp` instead of `timestamp`.

**Comment by jaygordon** [comment]
I'm in favor of avoiding SQL keywords where possible. It's true that TIDES doesn't necessary define a database schema but I think many TIDES adopters will indeed store these data in a SQL database, and it would be convenient for the db column names to match the spec.

In some cases a field name that happens to be a keyword in SQL (or in some scripting or programming language) also happens to be insufficiently descriptive. Two column names that come to mind are `timestamp` and `date`. Both are SQL keywords, and I anticipate that the presence of both columns in the same table (in `fare_transactions`, `passenger_events`, and `vehicle_locations`) will be a source of confusion for users who don't carefully read the documentation. Renaming `date` to `svc_date` or `service_date`, and renaming `timestamp` to `txn_time` or `transaction_time` might remind users that the former pertains to a business rule (a grouping of services or operations that start on some calendar date but might continue into a later date) and that the latter pertains to actual clock time.
