### ISSUE TITLE
🐛💻 – documentation edit links not useful, possibly misleading

### ISSUE THREAD

**Issue by botanize** [TIDES-transit/TIDES#83]
**Describe the problem**

Essentially all of the documentation pages on the gh-pages site are templates, and nearly all of the content is provided by including other markdown files. The edit links provide no way to edit the included documents. For example, the [index page](https://tides-transit.github.io/TIDES/main/) is a wrapper for README.md, but there's no way to edit README.md from an edit link.

In that sense, the edit links are really only useful for infrastructure developers to modify templates. Those developers would probably prefer using git directly instead of the GitHub edit interface.

For people who want to actually edit the README or CONTRIBUTING docs, there's no way to do that through edit links on the documentation site, which I find confusing.

The edit links are providing the wrong functionality to the wrong people.

**Steps to reproduce**

1. visit the [documentation home](https://tides-transit.github.io/TIDES/main/)
2. Click the "edit this page" icon on the upper right of the content
3. The editable content is only `{{ include_file('README.md', downshift_h1= False) }}`, there's no way to edit the included readme file.

**Comment by e-lo** [comment]
The edit link seems to have been removed and this can be closed.
