### ISSUE TITLE
🐛📄 – Drop operators table

### ISSUE THREAD

**Issue by gabriel-korbato** [TIDES-transit/TIDES#89]
**Describe the problem**
The operators table only has operator_id as a field, so it is not useful.

**Possible Solutions**
1. Drop the operators table.  Reintroduce it if and when the need arises.  
2. Add fields to the operators table to make it useful.  This would require requirements gathering, further thinking and discussion.

**Comment by botanize** [comment]
There's an option 3:

- leave as is, agencies may extend it as needed.

That seems to be the intention of the table from the TCRP Research Report.

**Comment by gabriel-korbato** [comment]
Couldn't agencies do that anyway, by adding a multi-column useful operators table as an extension even if we drop the single-column version of it from the spec?

**Comment by botanize** [comment]
Definitely. A good argument in favor of dropping it entirely.

**Comment by jlstpaul** [comment]
If we think it is likely that some data producers will want to define this table (and additional fields) I think we should keep the table as is (option 3).  It is much easier to leave out an optional table than it is to define a new one. And If we want to have future consistency in the naming of the table, we should just define it.  My preference is to leave this as is.

**Comment by botanize** [comment]
Agreed to leave as is in 2022-12-14 contributors meeting.
